---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(bipartite)
source("utils.R")
```

```{r}
networks_dir = "G:/My Drive/PhD/plant_pollinator_inter/Stouffer2014/raw_CSVs/networks/"
networks_classification_path = "G:/My Drive/PhD/plant_pollinator_inter/Stouffer2014/prepare_input_data/network_classification.csv"

networks_paths = list.files(networks_dir)
community_features = data.frame(matrix(ncol = 5, nrow = 0))
colnames(community_features) = c("network", "plant_richness", "pollinator_richness", "total_species_richness", "richness_ratio")
for (network_path in networks_paths)
{
  features = get_community_features(paste(networks_dir,network_path, sep=""))
  community_features[nrow(community_features) + 1,] = c(c(network_path),features)
}
write.csv(community_features, "community_features.csv", row.names = TRUE)
```


```{r}
networks_classfication = read_csv(networks_classification_path, show_col_types = FALSE)
networks_data_by_type = community_features %>% inner_join(networks_classfication, by="network")
kruskal.test(plant_richness~is_exotic, data=networks_data_by_type)
kruskal.test(pollinator_richness~is_exotic, data=networks_data_by_type)
kruskal.test(total_species_richness~is_exotic, data=networks_data_by_type)
kruskal.test(richness_ratio~is_exotic, data=networks_data_by_type)
```
