---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(bipartite)
source("utils.R")
```

```{r}
networks_dir = "G:/My Drive/PhD/plant_pollinator_inter/Stouffer2014/raw_CSVs/networks/"
species_classification_path = "G:/My Drive/PhD/plant_pollinator_inter/Stouffer2014/prepare_input_data/species_classification.csv"

networks_paths = list.files(networks_dir)
interaction_features = data.frame(matrix(ncol = 7, nrow = 0))
colnames(interaction_features) = c("network", "plant", "pollinator", "plant_dependance_on_pollinator", "plant_interactions_num", "pollinator_dependance_on_plant", "pollinator_interactions_num")
for (network_path in networks_paths)
{
  network_interaction_features = get_interaction_features(paste(networks_dir,network_path, sep=""))
  interaction_features = rbind(interaction_features, network_interaction_features)
}
interaction_features = interaction_features %>% filter(plant_dependance_on_pollinator > 0 | pollinator_dependance_on_plant > 0)
write.csv(interaction_features, "interaction_features.csv", row.names = TRUE)
```


```{r}
species_classification = read_csv(species_classification_path, show_col_types = FALSE)
interaction_features_by_type = interaction_features %>% left_join(species_classification, by=c("network" = "network", "plant" = "species"))

plant_pespective_model <- glm(interaction_features_by_type$plant_dependance_on_pollinator ~ interaction_features_by_type$is_exotic, family=binomial(link="logit"), weights=interaction_features_by_type$plant_interactions_num) # as per stouffer's clarification
summary(plant_pespective_model)

pollinator_pespective_model <- glm(interaction_features_by_type$pollinator_dependance_on_plant ~ interaction_features_by_type$is_exotic, family=binomial(link="logit"), weights=interaction_features_by_type$pollinator_interactions_num) # as per stouffer's clarification
summary(pollinator_pespective_model)
```

