---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(bipartite)
source("utils.R")
```

```{r}
networks_dir = "G:/My Drive/PhD/plant_pollinator_inter/Stouffer2014/raw_CSVs/networks/"
species_classification_path = "G:/My Drive/PhD/plant_pollinator_inter/Stouffer2014/prepare_input_data/species_classification.csv"

networks_paths = list.files(networks_dir)
pollinator_features = data.frame(matrix(ncol = 5, nrow = 0))
colnames(pollinator_features) = c("network","pollinator", "ranked_degree", "ranked_nestedness_contribution", "exotic_tendency")
for (network_path in networks_paths)
{
  if (network_path == "M_PL_038.csv")
  {
    network_pollinator_features = get_pollinator_features(paste(networks_dir,network_path, sep=""), species_classification_path)
    pollinator_features = rbind(pollinator_features, network_pollinator_features)
  }
}
write.csv(pollinator_features, "pollinator_species_features.csv", row.names = TRUE)
```
```{r}
# pending for Stouffer: do we need to work with the empirical tendencies as "p" or to consider the null tendencies as well somehow?
```

