---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(bipartite)
source("utils.R")
```


```{r}
networks_dir = "G:/My Drive/PhD/plant_pollinator_inter/Stouffer2014/raw_CSVs/networks/"
species_classification_path = "G:/My Drive/PhD/plant_pollinator_inter/Stouffer2014/prepare_input_data/species_classification.csv"

networks_paths = list.files(networks_dir)
species_features = data.frame(matrix(ncol = 4, nrow = 0))
colnames(species_features) = c("network", "species", "ranked_degree", "ranked_nestedness_contribution")
for (network_path in networks_paths)
{
  network_species_features = get_species_features(paste(networks_dir,network_path, sep=""))
  species_features = rbind(species_features, network_species_features)
}
write.csv(species_features, "plant_species_features.csv", row.names = TRUE)
```

```{r}
species_classification = read_csv(species_classification_path, show_col_types = FALSE)
species_data_by_type = species_features %>% inner_join(species_classification, by=c("network" = "network", "species" = "species"))
kruskal.test(ranked_degree~is_exotic, data=species_data_by_type)
kruskal.test(ranked_nestedness_contribution~is_exotic, data=species_data_by_type)
```

